export const API_ERROR = 'API_ERROR';
export const CONTACTS_POPULATE = 'CONTACT_POPULATE';
export const CONTACT_SELECT = 'CONTACT_SELECT';
export const CONTACT_UPDATE_CANCEL = 'CONTACT_UPDATE_CANCEL';
export const CONTACT_UPDATE_SAVE = 'CONTACT_UPDATE_SAVE';
export const LOADING_UPDATE = 'LOADING_UPDATE';
